# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X github.com/tfournier/gvm/cmd.version={{.Version}}

archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

sign:
  artifacts: none

release:
  prerelease: auto

brew:
  github:
    owner: tfournier
    name: homebrew-tap
  description: "GVM will allow you to easily install, use and/or delete Golang versions from the official servers."

scoop:
  bucket:
    owner: tfournier
    name: scoop-bucket
  description: "GVM will allow you to easily install, use and/or delete Golang versions from the official servers."

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  vendor: TFournier
  maintainer: Thomas FOURNIER <tfournier59@gmail.com>
  description: "GVM will allow you to easily install, use and/or delete Golang versions from the official servers."
  license: MIT
  formats:
    - deb

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


